run:
  concurrency: 0
  allow-parallel-runners: true
  allow-serial-runners: true
  tests: false
  go: '1.23'

linters:
  enable-all: true
  disable:
    - goimports # Not needed 
    - depguard # Not needed
    - gci # Encountering issues
    - gofmt # Replaced by gofumpt
    - nlreturn # Not needed
    - wsl # Too strict
    - wrapcheck # Not needed 
    - ireturn # Configuration is bugged
    - bodyclose # Lots of false positives
    - forcetypeassert # Not needed
    - mnd # Not needed
    - exhaustruct # Not needed
    - cyclop # Not needed
    - dupl # Not needed
    - varnamelen # Not needed
    - nonamedreturns # Not needed
    - iface # Not needed
    - godot # Not needed
    - gochecknoinits # Not needed
    - exportloopref # Deprecated

linters-settings:
  lll:
    line-length: 205
  funlen:
    lines: 130
    statements: 55
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  gocognit:
    min-complexity: 35
  goconst:
    min-len: 4
  nestif:
    min-complexity: 8
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)