[common.debug]
log_level = "info"
max_logs_to_keep = 10
max_log_lines = 5000
query_logging = true
enable_pprof = false
pprof_port = 6060

[common.rate_limit]
requests_per_second = 100.0
burst_size = 1

[common.circuit_breaker]
max_failures = 10
failure_threshold = 500
recovery_timeout = 1000

[common.postgresql]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
db_name = "postgres"

[common.redis]
host = "127.0.0.1"
port = 6379
username = ""
password = ""

[common.gemini_ai]
api_key = ""
model = "gemini-1.5-flash-latest"