[common]
version = 1

[common.debug]
# Log level (debug, info, warn, error)
log_level = "info"

# Maximum number of log files to keep before rotation
max_logs_to_keep = 10
# Maximum number of lines per log file
max_log_lines = 5000

# Enable pprof debugging endpoints
enable_pprof = false
# Port for pprof HTTP server if enabled
pprof_port = 6060

[common.uptrace]
# Uptrace DSN for telemetry (leave empty to disable)
dsn = ""
# Service name for telemetry
service_name = "rotector"
# Service version for telemetry
service_version = "1.0.0"
# Deployment environment (development, staging, production)
deploy_environment = "development"

[common.proxy]
# Default cooldown period in milliseconds for unspecified endpoints
default_cooldown = 5000
# Duration in milliseconds to mark a proxy as unhealthy after a timeout error
unhealthy_duration = 30000

# Endpoint-specific cooldown periods in milliseconds
[common.proxy.endpoints]
get_friend_count = { pattern = "friends.roblox.com/v1/users/{id}/friends/count", cooldown = 5000 }
get_friends = { pattern = "friends.roblox.com/v1/users/{id}/friends", cooldown = 5000 }
find_friends = { pattern = "friends.roblox.com/v1/users/{id}/friends/find", cooldown = 5000 }
user_info = { pattern = "users.roblox.com/v1/users/{id}", cooldown = 5000 }
user_info_batch = { pattern = "users.roblox.com/v1/users", cooldown = 5000 }
user_games = { pattern = "games.roblox.com/v2/users/{id}/games", cooldown = 5000 }
user_outfits = { pattern = "avatar.roblox.com/v2/avatar/users/{id}/outfits", cooldown = 6000 }
user_groups = { pattern = "groups.roblox.com/v1/users/{id}/groups/roles", cooldown = 5000 }
thumbnail_batch = { pattern = "thumbnails.roblox.com/v1/batch", cooldown = 1000 }
cdn_thumbnails = { pattern = "tr.rbxcdn.com/30DAY-Avatar-{hash}-Png/{id}/{id}/Avatar/Webp/noFilter", cooldown = 1000 }

[common.roverse]
# Domain for the roverse proxy service (leave empty to disable)
domain = ""
# Secret key for authentication
secret_key = ""
# Maximum concurrent requests to roverse
max_concurrent = 100

[common.circuit_breaker]
# Number of failures before circuit opens
max_failures = 10
# Request timeout in milliseconds
failure_threshold = 500
# Recovery delay in milliseconds
recovery_timeout = 30000

[common.retry]
# Maximum retry attempts
max_retries = 3
# Initial retry delay in milliseconds
delay = 4000
# Maximum retry delay in milliseconds
max_delay = 5000

[common.postgresql]
# Database hostname
host = "127.0.0.1"
# Database port
port = 5432
# Database username
user = "postgres"
# Database password
password = "postgres"
# Database name
db_name = "postgres"

# Maximum open connections
max_open_conns = 8
# Maximum idle connections
max_idle_conns = 8
# Connection lifetime in minutes
max_lifetime = 10
# Idle timeout in minutes
max_idle_time = 10

[common.redis]
# Redis hostname
host = "127.0.0.1"
# Redis port
port = 6379
# Redis username
username = ""
# Redis password
password = ""

[common.openai]
# Default model to use for AI requests
model = "gemini-2.0-flash"

[[common.openai.providers]]
name = "google"
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = ""
max_concurrent = 1000

[common.openai.providers.model_mappings]
"gemini-2.0-flash" = "models/gemini-2.0-flash"

[[common.openai.providers]]
name = "requesty"
base_url = "https://router.requesty.ai/v1"
api_key = ""
max_concurrent = 100

[common.openai.providers.model_mappings]
"gemini-2.0-flash" = "google/gemini-2.0-flash-001"
"gpt-4o-mini" = "openai/gpt-4o-mini-2024-07-18"
"qwq-32B" = "deepinfra/Qwen/QwQ-32B"
"deepseek-r1-distill-qwen-32b" = "novita/deepseek/deepseek-r1-distill-qwen-32b"
"deepseek-r1-distill-llama-70B" = "deepinfra/deepseek-ai/DeepSeek-R1-Distill-Llama-70B"
"llama-3.3-70B-instruct" = "nebius/meta-llama/Llama-3.3-70B-Instruct"

[common.discord]
# Self-bot token for server scanning
sync_token = ""
