[common.debug]
log_level = "info"
max_logs_to_keep = 10
max_log_lines = 5000
enable_pprof = false
pprof_port = 6060

[common.rate_limit]
requests_per_second = 100.0
burst_size = 1

[common.circuit_breaker]
max_failures = 10
failure_threshold = 500 # 500 milliseconds
recovery_timeout = 1000 # 1 second

[common.retry]
max_retries = 3
delay = 2000 # 2 seconds
max_delay = 5000 # 5 seconds

[common.postgresql]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
db_name = "postgres"
max_open_conns = 10
max_idle_conns = 10
max_lifetime = 30  # 30 minutes
max_idle_time = 10  # 10 minutes

[common.redis]
host = "127.0.0.1"
port = 6379
username = ""
password = ""

[common.gemini_ai]
api_key = ""
model = "gemini-1.5-flash-8b-latest"