[rpc.server]
# Host address to listen on
# Use "127.0.0.1" for local access only
# Use "0.0.0.0" to allow external connections
host = "127.0.0.1"

# Port number for the RPC server
# Default is 8080, but can be changed if needed
port = 8080

[rpc.ip]
# Enable checking of forwarded headers (X-Forwarded-For, etc.)
# Set to false if not using a reverse proxy
enable_header_check = true

# List of trusted proxy IPs that can set forwarded headers
# For local testing, you might want to add:
#   "127.0.0.0/8"      # Localhost
#   "10.0.0.0/8"       # Private network
#   "172.16.0.0/12"    # Private network
#   "192.168.0.0/16"   # Private network
trusted_proxies = []

# Headers to check for client IP, in order of precedence
# Standard headers used by various providers and proxies
custom_headers = [
    # Standard headers used by Amazon EC2, Heroku, and others
    "X-Client-IP",
    
    # CDN specific headers
    "CF-Connecting-IP",     # Cloudflare
    "Fastly-Client-Ip",     # Fastly CDN
    "True-Client-Ip",       # Akamai/Cloudflare
    
    # Nginx proxy/FastCGI
    "X-Real-IP",
    
    # Standard forwarded headers
    "X-Original-Forwarded-For",
    "X-Forwarded-For",
    "X-Forwarded",
    "Forwarded-For",
    "Forwarded"
]

# Allow local IPs (127.0.0.1, etc.) for development/testing
# WARNING: Do not enable in production!
allow_local_ips = false

[rpc.rate_limit]
# Maximum number of requests per second per IP
# Default is 5 requests per second
requests_per_second = 5.0

# Maximum burst size for rate limiting
# Default is 5 requests
burst_size = 5