[worker]
version = 1

# Delay between worker startups in milliseconds
startup_delay = 5000
# Request timeout in milliseconds
request_timeout = 15000

[worker.batch_sizes]
# Number of friends to process in one batch
friend_users = 200
# Number of group members to process in one batch
group_users = 200

# Number of users to check for bans in one batch
purge_users = 200
# Number of groups to check for bans in one batch
purge_groups = 100

# Number of group trackings to process in one batch
track_groups = 100

# Number of queue items to process in one batch
queue_items = 10

# Number of users to update thumbnails in one batch
thumbnail_users = 100
# Number of groups to update thumbnails in one batch 
thumbnail_groups = 100

# Maximum concurrent AI requests for outfit analysis
outfit_analysis = 10
# Maximum concurrent AI requests for user analysis
user_analysis = 10
# Maximum concurrent AI requests for user reason analysis
user_reason_analysis = 10
# Maximum concurrent AI requests for friend reason analysis
friend_reason_analysis = 10
# Maximum concurrent AI requests for group reason analysis
group_reason_analysis = 10
# Maximum concurrent AI requests for outfit reason analysis
outfit_reason_analysis = 10
# Maximum concurrent AI requests for message analysis
message_analysis = 5
# Maximum concurrent AI requests for ivan message analysis
ivan_message_analysis = 5

# Number of outfits to analyze in one AI request
outfit_analysis_batch = 16
# Number of users to analyze in one AI request
user_analysis_batch = 25
# Number of users to analyze in one user reason AI request
user_reason_analysis_batch = 10
# Number of users to analyze in one friend reason AI request
friend_reason_analysis_batch = 20
# Number of users to analyze in one group reason AI request
group_reason_analysis_batch = 20
# Number of users to analyze in one outfit reason AI request
outfit_reason_analysis_batch = 20
# Number of messages to analyze in one AI request
message_analysis_batch = 25
# Number of ivan messages to analyze in one AI request
ivan_message_analysis_batch = 100

[worker.threshold_limits]
# Maximum number of flagged users before stopping worker
flagged_users = 1000000

# Minimum number of flagged users needed to consider flagging a group
min_group_flagged_users = 10
# Minimum percentage of flagged users needed to flag a group
min_flagged_percentage = 40.0
# Flag group if flagged users count exceeds this value, regardless of percentage
min_flagged_override = 1000

# Maximum group members before skipping tracking
max_group_members_track = 20000

# Maximum game visits before skipping tracking
max_game_visits_track = 1000000

# Hamming distance threshold for considering outfit images as similar (lower = more strict)
image_similarity_threshold = 2

# Number of messages to accumulate before processing a channel batch
channel_process_threshold = 25

[worker.cloudflare]
# Cloudflare account ID
account_id = ""
# D1 database ID
database_id = ""
# API token with D1 access
api_token = ""
# API endpoint for D1 queries
api_endpoint = "https://api.cloudflare.com/client/v4"