basePath: /v1
definitions:
  internal_rest_types.Group:
    properties:
      confidence:
        type: number
      description:
        type: string
      downvotes:
        type: integer
      id:
        type: integer
      isLocked:
        type: boolean
      lastScanned:
        type: string
      lastUpdated:
        type: string
      lastViewed:
        type: string
      name:
        type: string
      owner:
        $ref: '#/definitions/types.GroupUser'
      reasons:
        $ref: '#/definitions/internal_rest_types.Reasons'
      reputation:
        type: integer
      shout:
        $ref: '#/definitions/types.GroupShout'
      thumbnailUrl:
        type: string
      upvotes:
        type: integer
    type: object
  internal_rest_types.Reason:
    properties:
      confidence:
        type: number
      evidence:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  internal_rest_types.Reasons:
    additionalProperties:
      $ref: '#/definitions/internal_rest_types.Reason'
    type: object
  internal_rest_types.User:
    properties:
      confidence:
        type: number
      createdAt:
        type: string
      description:
        type: string
      displayName:
        type: string
      downvotes:
        type: integer
      flaggedContent:
        items:
          type: string
        type: array
      flaggedGroups:
        items:
          type: integer
        type: array
      friends:
        items:
          $ref: '#/definitions/types.UserFriend'
        type: array
      games:
        items:
          $ref: '#/definitions/types.UserGame'
        type: array
      groups:
        items:
          $ref: '#/definitions/types.UserGroup'
        type: array
      id:
        type: integer
      isBanned:
        type: boolean
      lastScanned:
        type: string
      lastUpdated:
        type: string
      lastViewed:
        type: string
      name:
        type: string
      reasons:
        $ref: '#/definitions/internal_rest_types.Reasons'
      reputation:
        type: integer
      thumbnailUrl:
        type: string
      upvotes:
        type: integer
    type: object
  types.GetGroupResponse:
    properties:
      group:
        $ref: '#/definitions/internal_rest_types.Group'
      status:
        $ref: '#/definitions/types.GroupStatus'
    type: object
  types.GetUserResponse:
    properties:
      status:
        $ref: '#/definitions/types.UserStatus'
      user:
        $ref: '#/definitions/internal_rest_types.User'
    type: object
  types.GroupShout:
    properties:
      content:
        type: string
      poster:
        $ref: '#/definitions/types.GroupUser'
    type: object
  types.GroupStatus:
    enum:
    - flagged
    - confirmed
    - cleared
    - unflagged
    type: string
    x-enum-varnames:
    - GroupStatusFlagged
    - GroupStatusConfirmed
    - GroupStatusCleared
    - GroupStatusUnflagged
  types.GroupUser:
    properties:
      displayName:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  types.UserFriend:
    properties:
      displayName:
        type: string
      hasVerifiedBadge:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
  types.UserGame:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  types.UserGroup:
    properties:
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
  types.UserStatus:
    enum:
    - flagged
    - confirmed
    - cleared
    - unflagged
    type: string
    x-enum-varnames:
    - UserStatusFlagged
    - UserStatusConfirmed
    - UserStatusCleared
    - UserStatusUnflagged
info:
  contact: {}
  description: REST API for Rotector
  license:
    name: GPL-2.0
    url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
  title: Rotector API
  version: "1.0"
paths:
  /groups/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves detailed information about a group by their ID
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetGroupResponse'
        "429":
          description: Rate limit exceeded
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get group information
      tags:
      - groups
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves detailed information about a user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetUserResponse'
        "429":
          description: Rate limit exceeded
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get user information
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: 'API key must be provided as: Bearer <api_key>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
